### ISSUE TITLE
Axoloti control board schematics

### ISSUE THREAD

**Issue by Thierry-Cheverney** [TomWhitwell/axoloti_ctrl#1]
Hello,
I am looking for the Axoloti Control Board Shematics and BOM.
I got the Tom Whittwell GitHub account link from Thonk in order to get these documents.
Thanks for answers. Thierry

**Comment by TomWhitwell** [comment]
Just added a schematic for you: https://github.com/TomWhitwell/Axo-Control/blob/master/Collateral/axo_control_schematic.pdf

**Comment by Thierry-Cheverney** [comment]
Thanks very much for your help. Thierry
